from django.db import models

# Create your models here.
class SprzedazWiersz(models.Model):
    LpSprzedazy = models.IntegerField()
    NrKontrahenta = models.CharField(max_length=30, default='brak')
    NazwaKontrahenta = models.CharField(max_length=240)
    AdresKontrahenta = models.CharField(max_length=240)
    DowodSprzedazy = models.CharField(max_length=240)
    DataWystawienia = models.DateField()
    DataSprzedazy = models.DateField(null=True)
    K_10 = models.DecimalField(max_digits=16, decimal_places=2, null=True)
    K_11 = models.DecimalField(max_digits=16, decimal_places=2, null=True)
    K_12 = models.DecimalField(max_digits=16, decimal_places=2, null=True)
    K_13 = models.DecimalField(max_digits=16, decimal_places=2, null=True)
    K_14 = models.DecimalField(max_digits=16, decimal_places=2, null=True)
    K_15 = models.DecimalField(max_digits=16, decimal_places=2, null=True)
    K_16 = models.DecimalField(max_digits=16, decimal_places=2, null=True)
    K_17 = models.DecimalField(max_digits=16, decimal_places=2, null=True)
    K_18 = models.DecimalField(max_digits=16, decimal_places=2, null=True)
    K_19 = models.DecimalField(max_digits=16, decimal_places=2, null=True)
    K_20 = models.DecimalField(max_digits=16, decimal_places=2, null=True)
    K_21 = models.DecimalField(max_digits=16, decimal_places=2, null=True)
    K_22 = models.DecimalField(max_digits=16, decimal_places=2, null=True)
    K_23 = models.DecimalField(max_digits=16, decimal_places=2, null=True)
    K_24 = models.DecimalField(max_digits=16, decimal_places=2, null=True)
    K_25 = models.DecimalField(max_digits=16, decimal_places=2, null=True)
    K_26 = models.DecimalField(max_digits=16, decimal_places=2, null=True)
    K_27 = models.DecimalField(max_digits=16, decimal_places=2, null=True)
    K_28 = models.DecimalField(max_digits=16, decimal_places=2, null=True)
    K_29 = models.DecimalField(max_digits=16, decimal_places=2, null=True)
    K_30 = models.DecimalField(max_digits=16, decimal_places=2, null=True)
    K_31 = models.DecimalField(max_digits=16, decimal_places=2, null=True)
    K_32 = models.DecimalField(max_digits=16, decimal_places=2, null=True)
    K_33 = models.DecimalField(max_digits=16, decimal_places=2, null=True)
    K_34 = models.DecimalField(max_digits=16, decimal_places=2, null=True)
    K_35 = models.DecimalField(max_digits=16, decimal_places=2, null=True)
    K_36 = models.DecimalField(max_digits=16, decimal_places=2, null=True)
    K_37 = models.DecimalField(max_digits=16, decimal_places=2, null=True)
    K_38 = models.DecimalField(max_digits=16, decimal_places=2, null=True)
    K_39 = models.DecimalField(max_digits=16, decimal_places=2, null=True)

