class IterRegistry(type):
    def __iter__(cls):
        return iter(cls._registry)


class Tags(metaclass=IterRegistry):
    _registry = []

    def __init__(self, ns, tags, date_fields, money_fields, quantity_fields):
        self._registry.append(self)
        self.ns = ns
        self.tags = tags
        self.date_fields = date_fields
        self.money_fields = money_fields
        self.quantity_fields = quantity_fields


JPK_VAT = Tags(
    '{http://jpk.mf.gov.pl/wzor/2016/10/26/10261/}',
    {'SprzedazWiersz': ['LpSprzedazy',
                        'NrKontrahenta',
                        'NazwaKontrahenta',
                        'AdresKontrahenta',
                        'DowodSprzedazy',
                        'DataWystawienia',
                        'DataSprzedazy',
                        'K_10',
                        'K_11',
                        'K_12',
                        'K_13',
                        'K_14',
                        'K_15',
                        'K_16',
                        'K_17',
                        'K_18',
                        'K_19',
                        'K_20',
                        'K_21',
                        'K_22',
                        'K_23',
                        'K_24',
                        'K_25',
                        'K_26',
                        'K_27',
                        'K_28',
                        'K_29',
                        'K_30',
                        'K_31',
                        'K_32',
                        'K_33',
                        'K_34',
                        'K_35',
                        'K_36',
                        'K_37',
                        'K_38',
                        'K_39'],
    'ZakupWiersz': ['LpZakupu',
                    'NrDostawcy',
                    'NazwaDostawcy',
                    'AdresDostawcy',
                    'DowodZakupu',
                    'DataZakupu',
                    'DataWplywu',
                    'K_43',
                    'K_44',
                    'K_45',
                    'K_46',
                    'K_47',
                    'K_48',
                    'K_49',
                    'K_50'],
    },
    ['DataWystawienia',
     'DataSprzedazy',
     'DataZakupu',
     'DataWplywu'],
    ['K_10',
     'K_11',
     'K_12',
     'K_13',
     'K_14',
     'K_15',
     'K_16',
     'K_17',
     'K_18',
     'K_19',
     'K_20',
     'K_21',
     'K_22',
     'K_23',
     'K_24',
     'K_25',
     'K_26',
     'K_27',
     'K_28',
     'K_29',
     'K_30',
     'K_31',
     'K_32',
     'K_33',
     'K_34',
     'K_35',
     'K_36',
     'K_37',
     'K_38',
     'K_39',
     'K_43',
     'K_44',
     'K_45',
     'K_46',
     'K_47',
     'K_48',
     'K_49',
     'K_50' ],
    ['LpSprzedazy',
     'LpZakupu',],
)

JPK_KR = Tags(
    '{http://jpk.mf.gov.pl/wzor/2016/03/09/03091/}',
    {'ZOiS': ['KodKonta',
              'OpisKonta',
              'TypKonta',
              'KodZespolu',
              'OpisZespolu',
              'KodKategorii',
              'OpisKategorii',
              'KodPodkategorii',
              'OpisPodkategorii',
              'BilansOtwarciaWinien',
              'BilansOtwarciaMa',
              'ObrotyWinien',
              'ObrotyMa',
              'ObrotyWinienNarast',
              'ObrotyMaNarast',
              'SaldoWinien',
              'SaldoMa'],
    'Dziennik': ['LpZapisuDziennika',
                 'NrZapisuDziennika',
                 'OpisDziennika',
                 'NrDowoduKsiegowego',
                 'RodzajDowodu',
                 'DataOperacji',
                 'DataDowodu',
                 'DataKsiegowania',
                 'KodOperatora',
                 'OpisOperacji',
                 'DziennikKwotaOperacji'],
    'KontoZapis': ['LpZapisu',
                   'NrZapisu',
                   'KodKontaWinien',
                   'KwotaWinien',
                   'KwotaWinienWaluta',
                   'KodWalutyWinien',
                   'OpisZapisuWinien',
                   'KodKontaMa',
                   'KwotaMa',
                   'KwotaMaWaluta',
                   'KodWalutyMa',
                   'OpisZapisuMa'],
    'KontoZapisRestructured': ['LpZapisu',
                               'NrZapisu',
                               'KwotaWinien',
                               'KwotaWinienWaluta',
                               'KodWalutyWinien',
                               'OpisZapisuWinien',
                               'KwotaMa',
                               'KwotaMaWaluta',
                               'KodWalutyMa',
                               'OpisZapisuMa'],
    },
    ['DataOperacji',
     'DataDowodu',
     'DataKsiegowania',],
    ['BilansOtwarciaWinien',
     'BilansOtwarciaMa',
     'ObrotyWinien',
     'ObrotyMa',
     'ObrotyWinienNarast',
     'ObrotyMaNarast',
     'SaldoWinien',
     'SaldoMa',
     'DziennikKwotaOperacji',
     'KwotaWinien',
     'KwotaMa',],
    ['LpZapisuDziennika',
     'LpZapisu',]
)

